### PR TITLE
Fixed issue with commands with leading whitespaces

### LINKED ISSUE #161: Commands with leading spaces not executed
Example : `  add /movie 1 /rating 1 /date 29-10-2022 /genre 6`
Command not recognised by application due to leading whitespaces.

### PR DESCRIPTION
**Pull request by redders7**
Fixes #161

### CODE REVIEW

File: src/main/java/seedu/duke/Parser.java [hunk 1]
```diff
@@ -59,7 +59,8 @@ public Parser(ReviewList reviewList) {
 
     //@@author redders7
     public String[] getCommandWord(String input) {
-        String[] result = input.split(" ");
+        String trimmedInput = input.trim();
+        String[] result = trimmedInput.split(" ");
```
Comment (matthewphua) [inline src/main/java/seedu/duke/Parser.java:63]: This should work :)

**Review by matthewphua — APPROVED** [review]
